DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE PRODUCT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(500),
    PRICE DECIMAL(10, 2) NOT NULL
);

DROP TABLE IF EXISTS USERTABLE;

CREATE TABLE USERTABLE (
      id BIGINT AUTO_INCREMENT PRIMARY KEY,
      email VARCHAR(255),
      password VARCHAR(255),
       role VARCHAR(50)
);